### ISSUE TITLE
Support RAILS_ENV=production

### ISSUE THREAD

**Issue by razorsedge** [ConradIrwin/showterm.io#26]
I would like to see a production deployment that did not pull in all the development libraries and optimized for speed.  I made a feeble attempt with
```
bundle exec rake db:create db:migrate db:seed RAILS_ENV=production
bin/rails server --environment=production
```
but that ended with the main website at http://localhost:3000 not fully loading graphics and CSS.

**Comment by razorsedge** [comment]
Ah, silly me found `bundle exec rake assets:precompile RAILS_ENV=production` in the README.fedora.md.

I would still ask that things like pry and Skylight (and any others) be set into a development group in the Gemfile.  And somehow allow a choice of SQL backends.

**Comment by ConradIrwin** [comment]
Hey @razorsedge! Great ideas :). Please send pull requests if you end up making any changes on your end.
