### ISSUE TITLE
How to increase font size?

### ISSUE THREAD

**Issue by razorsedge** [ConradIrwin/showterm.io#27]
Not knowing much about CSS, I am trying to figure out how I can increase the font size of showterm.  I am going to be embedding showterm in my presentation and I need to make sure the code is readable to folks in the back.  Should I be looking in `app/assets/stylesheets`?  What bits should I try toggling?

**Comment by ConradIrwin** [comment]
The easiest way is probably just to add:

html{ zoom: 200%; }

or however much zoom you need.
