### ISSUE TITLE
images doesn't load

### ISSUE THREAD

**Issue by diwu1989** [ConradIrwin/showterm.io#28]
I forked and deployed to heroku.
Images are not loading:
![image](https://cloud.githubusercontent.com/assets/380950/6654525/bcff4ac0-ca87-11e4-9d90-d85c14c7deef.png)

what should I do to get the images to show?

**Comment by ConradIrwin** [comment]
I forgot to commit them — those images don't load on showterm.io either :).
Feel free to delete whatever code is trying to load them (I think I just
copy-pasted some jquery slider plugin).

Conrad
