### ISSUE TITLE
// FIXME... just using 'j' leaves everything HTML escaped too

### ISSUE THREAD

**Issue by zotherstupidguy** [ConradIrwin/showterm.io#39]
in https://github.com/ConradIrwin/showterm.io/blob/master/app/views/scripts/view.html#L6

// FIXME... just using 'j' leaves everything HTML escaped too

what does it exactly refer to?

**Comment by ConradIrwin** [comment]
I think it may have been fixed using `raw_json` already. please feel free to delete the comment :)

**Comment by zotherstupidguy** [comment]
Allright :+1:
