### ISSUE TITLE
raw_json method alternative 

### ISSUE THREAD

**Issue by zotherstupidguy** [ConradIrwin/showterm.io#41]
I am trying to ditch Rails, and put showterm player in a Sinatra app along with old script linux command (not the *improved version in showterm). 

What is a good alternative for the raw_json method in Standard Library or a standalone gem other than active_support which is what raw_json is using?
 
https://github.com/ConradIrwin/showterm.io/blob/master/app/helpers/scripts_helper.rb#L3-L14

**Comment by ConradIrwin** [comment]
`raw` is only needed to stop rails HTML-escaping the result, the .to_json.gsub() is the only bit you need, and the standard libraries' JSON will work just fine.

**Comment by zotherstupidguy** [comment]
thanks for the tip, i have been running into some weird issues if the replay contains emacs, is there a way to debug showterm to understand which sequence is causing the error and maybe trace it?

**Comment by ConradIrwin** [comment]
you might want to try upgrading the js emulator, the showterm code itself doesn't do much with the values

**Comment by zotherstupidguy** [comment]
Thanks again!! really appreciate it! I did upgrade the term.js file but still getting the same error, "Uncaught TypeError: Cannot set property 'innerHTML' of undefined"  the latest term.js file "this.children[y].innerHTML = out;" 

I could help to track down whats wrong if i am sure it is not something related to the showterm improved script implementation as i am not using it for this quick hack. so I guess its a term.js issue now!

**Comment by ConradIrwin** [comment]
The `script` implementation in the repo is just for mac users, it's probably out of date by now too :) I don't think I changed anything

**Comment by zotherstupidguy** [comment]
I think i was getting errors due to big terminal dimensions!!
